# golangci-lint 配置文件
# 用于代码质量检查和 CI/CD

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - third_party
    - testdata
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck      # 检查错误处理
    - gosimple      # 简化代码
    - govet         # Go 标准检查
    - ineffassign   # 检查无效赋值
    - staticcheck   # 静态分析
    - typecheck     # 类型检查
    - unused        # 检查未使用的常量、变量等
    - gofmt         # 代码格式化
    - goimports     # import 排序
    - misspell      # 拼写检查
    - goconst       # 检查可以提取为常量的重复字符串
    - dupl          # 检查重复代码
    - gosec         # 安全检查
    - bodyclose     # 检查 HTTP body 是否关闭
    - noctx         # 检查 HTTP 请求是否使用 context
    - errname       # 检查错误命名
    - errorlint     # 错误处理最佳实践
    - exportloopref # 检查循环变量导出问题
  disable:
    - exhaustive    # 太严格
    - exhaustruct   # 太严格
    - varnamelen    # 太严格
    - gochecknoglobals # 在某些场景需要全局变量

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/erweixin/go-genai-stack
  
  misspell:
    locale: US
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  dupl:
    threshold: 100
  
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # 审计未检查的错误
      - G204  # 审计命令执行
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - paramTypeCombine
      - unnamedResult

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # 排除测试文件的某些检查
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    
    # 排除生成的文件
    - path: \.pb\.go$
      linters:
        - all
    
    # 排除特定错误消息
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
    
    # 允许在 main 和 init 函数中使用 panic
    - text: "Use of panic detected"
      linters:
        - gosec
      path: cmd/
    
    # 允许在测试中使用 MD5（不用于加密）
    - text: "Use of weak cryptographic primitive"
      linters:
        - gosec
      path: _test\.go

severity:
  default-severity: warning
  rules:
    - linters:
        - dupl
      severity: info

