# golangci-lint configuration for Go-GenAI-Stack
# Compatible with golangci-lint v1.64.8+

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - vendor
    - .git
    - .github
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  max-issues-per-linter: 50
  max-same-issues: 3

linters-settings:
  goimports:
    local-prefixes: github.com/erweixin/go-genai-stack
  
  gofmt:
    simplify: true
  
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment  # Already optimized manually

linters:
  disable-all: true
  enable:
    # Code formatting (auto-fixable)
    - gofmt         # Code formatting
    - goimports     # Import sorting
    
    # Code quality checks
    - errcheck      # Check unchecked errors
    - gosimple      # Simplify code suggestions
    - govet         # Go official checker
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Unused code detection
    
    # Optional checks
    - misspell      # Spell checker
    
  # Note: typecheck is disabled because it may produce false positives
  # Actual type checking is guaranteed by `go build` and `go test`
