# golangci-lint 配置文件
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # 检查错误处理
    - gosimple      # 简化代码
    - govet         # 静态分析
    - ineffassign   # 检测无效赋值
    - staticcheck   # 静态检查
    - unused        # 检测未使用的代码
    - gofmt         # 格式检查
    - goimports     # import 排序
    - misspell      # 拼写检查
    - revive        # 代码质量检查
    - gosec         # 安全检查
    - gocyclo       # 圈复杂度检查
    - goconst       # 常量检查
    - dupl          # 重复代码检查
    - gocritic      # 代码审查

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  dupl:
    threshold: 100
  
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
  
  gosec:
    excludes:
      - G104  # 允许未检查的错误（某些情况下）
  
  misspell:
    locale: US

issues:
  exclude-rules:
    # 排除测试文件的某些规则
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
    
    # 排除生成的代码
    - path: (^|/)vendor($|/)
      linters:
        - all
    
    # 排除某些目录
    - path: infrastructure/
      linters:
        - gosec
  
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

